---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# The Python Programming Language: Functions

<br>
`add_numbers` is a function that takes two numbers and adds them together.

In [1]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

<br>
`add_numbers` updated to take an optional 3rd parameter. Using `print` allows printing of multiple expressions within a single cell.

In [2]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


<br>
`add_numbers` updated to take an optional flag parameter.

In [5]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is true!
3


<br>
Assign function `add_numbers` to variable `a`.

In [6]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

3

<br>
# The Python Programming Language: Types and Sequences

<br>
Use `type` to return the object's type.

In [7]:
type('This is a string')

str

In [8]:
type(None)

NoneType

In [9]:
type(1)

int

In [10]:
type(1.0)

float

In [11]:
type(add_numbers)

function

<br>
Tuples are an immutable data structure (cannot be altered).

In [12]:
x = (1, 'a', 2, 'b')
type(x)

tuple

<br>
Lists are a mutable data structure.

In [13]:
x = [1, 'a', 2, 'b']
type(x)

list

<br>
Use `append` to append an object to a list.

In [14]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


<br>
This is an example of how to loop through each item in the list.

In [15]:
for item in x:
    print(item)

1
a
2
b
3.3


<br>
Or using the indexing operator:

In [16]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


<br>
Use `+` to concatenate lists.

In [33]:
abc=[1,2] + [3,4]
for x in abc:
    print(x+1)
print(abc)

abc=[x+1 for x in abc]
print(abc)

2
3
4
5
[1, 2, 3, 4]
[2, 3, 4, 5]


<br>
Use `*` to repeat lists.

In [20]:
[1]*10

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

<br>
Use the `in` operator to check if something is inside a list.

In [35]:
5 in [1, 2, 3]

False

<br>
Now let's look at strings. Use bracket notation to slice a string.

In [36]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters


T
T
Th


<br>
This will return the last element of the string.

In [37]:
x[-1]

'g'

<br>
This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [38]:
x[-4:-2]

'ri'

<br>
This is a slice from the beginning of the string and stopping before the 3rd element.

In [39]:
x[:3]

'Thi'

<br>
And this is a slice starting from the 4th element of the string and going all the way to the end.

In [40]:
x[3:]

's is a string'

In [41]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)


Christopher Brooks
ChristopherChristopherChristopher
True


<br>
`split` returns a list of all the words in a string, or a list split on a specific character.

In [42]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks


<br>
Make sure you convert objects to strings before concatenating.

In [43]:
'Chris' + 2

TypeError: must be str, not int

In [44]:
'Chris' + str(2)

'Chris2'

<br>
Dictionaries associate keys with values.

In [45]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator


'brooksch@umich.edu'

In [48]:
x['Kevyn Collins-Thompson'] = 'what'
x['Kevyn Collins-Thompson']

'what'

<br>
Iterate over all of the keys:

In [73]:
for k in x:
    print(k)

Christopher
Brooks
brooksch@umich.edu
Ann Arbor


<br>
Iterate over all of the values:

In [54]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
what


<br>
Iterate over all of the items in the list:

In [58]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
what


<br>
You can unpack a sequence into different variables:

In [59]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [60]:
fname

'Christopher'

In [61]:
lname

'Brooks'

<br>
Make sure the number of values you are unpacking matches the number of variables being assigned.

In [62]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

ValueError: too many values to unpack (expected 3)

<br>
# The Python Programming Language: More on Strings

In [64]:
print('Chris' + 2)

TypeError: must be str, not int

In [63]:
print('Chris' + str(2))

Chris2


<br>
Python has a built in method for convenient string formatting.

In [65]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


<br>
# Reading and Writing CSV files

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [69]:
import csv

%precision 2

csvfile= open('mpg.csv')
mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

<br>
`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 234 dictionaries.

In [70]:
len(mpg)

234

<br>
`keys` gives us the column names of our csv.

In [71]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

<br>
This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

In [80]:
sum(float(d['cty']) for d in mpg) / len(mpg)
sum=float(0)
for d in mpg:
    sum=sum+float(d['cty'])
print(sum)

TypeError: 'int' object is not callable

<br>
Similarly this is how to find the average hwy fuel economy across all cars.

In [ ]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

<br>
Use `set` to return the unique values for the number of cylinders the cars in our dataset have.

In [85]:
cylinders = set(d['cyl'] for d in mpg)
cylinders


{'4', '5', '6', '8'}

<br>
Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.

In [91]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

<br>
Use `set` to return the unique values for the class types in our dataset.

In [92]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

<br>
And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [95]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

<br>
# The Python Programming Language: Dates and Times

In [2]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [3]:
tm.time()

1594918511.9173017

<br>
Convert the timestamp to datetime.

In [4]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 7, 16, 16, 55, 21, 56147)

<br>
Handy datetime attributes:

In [ ]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

<br>
`timedelta` is a duration expressing the difference between two dates.

In [7]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(100)

<br>
`date.today` returns the current local date.

In [8]:
today = dt.date.today()

In [9]:
today - delta # the date 100 days ago

datetime.date(2020, 4, 7)

In [10]:
today > today-delta # compare dates

True

<br>
# The Python Programming Language: Objects and map()

<br>
An example of a class in python:

In [11]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [13]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


<br>
Here's an example of mapping the `min` function between two lists.

In [14]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

<br>
Now let's iterate through the map object to see the values.

In [21]:
for item in cheapest:
    print(item)
    
    
people=['Dr. Chris Brooks','Dr. Key Collins-th','Dr. VG fwefew via','Dr. Dan Romero']

def split_title_and_name(person):
    title=person.split()[0]
    lastname=person.split()[-1]
    return '{} {}'.format(title,lastname)


lst=list()
for name in people:
    x= name.split()[0]+' '+name.split()[-1]
    lst.append(x)
print(lst)
print(list(map(split_title_and_name,people)))

['Dr. Brooks', 'Dr. Collins-th', 'Dr. via', 'Dr. Romero']
['Dr. Brooks', 'Dr. Collins-th', 'Dr. via', 'Dr. Romero']


<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [22]:
my_function = lambda a, b, c : a + b

In [23]:
my_function(1, 2, 3)

3

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [111]:
my_list = []
for number in range(0, 10):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0, 2, 4, 6, 8]

<br>
Now the same thing but with list comprehension.

In [24]:
my_list = [number for number in range(0,10) if number % 2 == 0]
my_list

[0, 2, 4, 6, 8]

In [27]:
alphabet='abcdef'
digits='012345'

mylist=[i+x+j+y for i in alphabet for j in digits for x in alphabet for y in digits]
print(mylist)

['aa00', 'aa01', 'aa02', 'aa03', 'aa04', 'aa05', 'ab00', 'ab01', 'ab02', 'ab03', 'ab04', 'ab05', 'ac00', 'ac01', 'ac02', 'ac03', 'ac04', 'ac05', 'ad00', 'ad01', 'ad02', 'ad03', 'ad04', 'ad05', 'ae00', 'ae01', 'ae02', 'ae03', 'ae04', 'ae05', 'af00', 'af01', 'af02', 'af03', 'af04', 'af05', 'aa10', 'aa11', 'aa12', 'aa13', 'aa14', 'aa15', 'ab10', 'ab11', 'ab12', 'ab13', 'ab14', 'ab15', 'ac10', 'ac11', 'ac12', 'ac13', 'ac14', 'ac15', 'ad10', 'ad11', 'ad12', 'ad13', 'ad14', 'ad15', 'ae10', 'ae11', 'ae12', 'ae13', 'ae14', 'ae15', 'af10', 'af11', 'af12', 'af13', 'af14', 'af15', 'aa20', 'aa21', 'aa22', 'aa23', 'aa24', 'aa25', 'ab20', 'ab21', 'ab22', 'ab23', 'ab24', 'ab25', 'ac20', 'ac21', 'ac22', 'ac23', 'ac24', 'ac25', 'ad20', 'ad21', 'ad22', 'ad23', 'ad24', 'ad25', 'ae20', 'ae21', 'ae22', 'ae23', 'ae24', 'ae25', 'af20', 'af21', 'af22', 'af23', 'af24', 'af25', 'aa30', 'aa31', 'aa32', 'aa33', 'aa34', 'aa35', 'ab30', 'ab31', 'ab32', 'ab33', 'ab34', 'ab35', 'ac30', 'ac31', 'ac32', 'ac33', 'ac34',

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [28]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [34]:

z=[1,2,3]
p=np.array(z)
p


array([1, 2, 3])

<br>
Or just pass in a list directly

In [56]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [46]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

m=np.array([[1,2],[3,4]])
m

array([[1, 2],
       [3, 4]])

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [37]:
m.shape

(2, 3)

<br>
`arange` returns evenly spaced values within a given interval.

In [38]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [51]:
n = n.reshape(5, 3) # reshape array to be 3x5
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [40]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

<br>
`resize` changes the shape and size of array in-place.

In [50]:
o.resize(3, 3)
o

n.resize(5,3)
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [52]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [67]:
print(np.zeros([2, 3]))
print(np.zeros((2, 3),int))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[0 0 0]
 [0 0 0]]


<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [54]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [57]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

<br>
Create an array using repeating list (or see `np.tile`)

In [58]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [59]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
#### Combining Arrays

In [63]:
p = np.ones((2, 3),int)
p

array([[1, 1, 1],
       [1, 1, 1]])

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [73]:
v=np.vstack([p, 2*p])
print(np.shape(v))
print(v)

(4, 3)
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [74]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [77]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]
print(type(x))

[5 7 9]
[-3 -3 -3]
<class 'numpy.ndarray'>


In [78]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[ 0.25  0.4   0.5 ]


In [79]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [ ]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

In [81]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array
print(z)

2
[[ 4  5  6]
 [16 25 36]]


<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [82]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>
The shape of array `z` is `(2,3)` before transposing.

In [83]:
z.shape

(2, 3)

<br>
Use `.T` to get the transpose.

In [84]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [85]:
z.T.shape

(3, 2)

<br>
Use `.dtype` to see the data type of the elements in the array.

In [86]:
z.dtype

dtype('int64')

<br>
Use `.astype` to cast to a specific type.

In [87]:
z = z.astype('f')
z.dtype

dtype('float32')

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [88]:
a = np.array([-4, -2, 1, 3, 5])

In [89]:
a.sum()

3

In [90]:
a.max()

5

In [91]:
a.min()

-4

In [92]:
a.mean()

0.59999999999999998

In [93]:
a.std()

3.2619012860600183

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [94]:
a.argmax()

4

In [95]:
a.argmin()

0

<br>
## Indexing / Slicing

In [96]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [97]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [98]:
s[1:5]

array([ 1,  4,  9, 16])

<br>
Use negatives to count from the back.

In [99]:
s[-4:]

array([ 81, 100, 121, 144])

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [100]:
s[-5::-2]

array([64, 36, 16,  4,  0])

<br>
Let's look at a multidimensional array.

In [101]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Use bracket notation to slice: `array[row, column]`

In [102]:
r[2, 2]

14

<br>
And use : to select a range of rows or columns

In [103]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [104]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [105]:
r[-1, ::2]

array([30, 32, 34])

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [106]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [107]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [108]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [112]:
r2[:] = 5
r2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

<br>
`r` has also been changed!

In [113]:
r

array([[ 5,  5,  5,  3,  4,  5],
       [ 5,  5,  5,  9, 10, 11],
       [ 5,  5,  5, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [114]:
r_copy = r.copy()
r_copy

array([[ 5,  5,  5,  3,  4,  5],
       [ 5,  5,  5,  9, 10, 11],
       [ 5,  5,  5, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [115]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 5  5  5  3  4  5]
 [ 5  5  5  9 10 11]
 [ 5  5  5 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [116]:
test = np.random.randint(0, 10, (4,3))
test

array([[1, 6, 5],
       [4, 5, 0],
       [2, 6, 7],
       [1, 6, 1]])

<br>
Iterate by row:

In [117]:
for row in test:
    print(row)

[1 6 5]
[4 5 0]
[2 6 7]
[1 6 1]


<br>
Iterate by index:

In [118]:
for i in range(len(test)):
    print(test[i])

[1 6 5]
[4 5 0]
[2 6 7]
[1 6 1]


<br>
Iterate by row and index:

In [121]:
for i, row in enumerate(test):
    print(i,row)

0 [1 6 5]
1 [4 5 0]
2 [2 6 7]
3 [1 6 1]


<br>
Use `zip` to iterate over multiple iterables.

In [122]:
test2 = test**2
test2

array([[ 1, 36, 25],
       [16, 25,  0],
       [ 4, 36, 49],
       [ 1, 36,  1]])

In [124]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)
print(test+test2)

[1 6 5] + [ 1 36 25] = [ 2 42 30]
[4 5 0] + [16 25  0] = [20 30  0]
[2 6 7] + [ 4 36 49] = [ 6 42 56]
[1 6 1] + [ 1 36  1] = [ 2 42  2]
[[ 2 42 30]
 [20 30  0]
 [ 6 42 56]
 [ 2 42  2]]


In [155]:
# Quiz
r= np.arange(36).reshape(6,6)
r[5,5]=10
print(r)
print(r.argmax())
print(r.max())
r[:,::5]

r[0:6,::-10]

r.reshape(36)[::7]

r[2:4,2:4]


np.random.randint(0,10,(2,1))



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 10]]
34
34


array([[5],
       [6]])

In [ ]:
x=np.array([])